[package]
name = "fe-mir"
version = "0.13.0-alpha"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"

[dependencies]
fe-common = { path = "../common", version = "^0.13.0-alpha" }
fe-parser = { path = "../parser", version = "^0.13.0-alpha" }
fe-analyzer = { path = "../analyzer", version = "^0.13.0-alpha" }
salsa = "0.16.1"
smol_str = "0.1.21"
num-bigint = "0.4.3"
id-arena = "2.2.1"
fxhash = "0.2.1"