// An impl or a const expression can make a recursive type grow where its
// field types do not.
pub trait Next {
    type Out
}

impl Next for u256 {
    type Out = Grow<[u256; 1]>
}

impl<T> Next for [T; 1] {
    type Out = Grow<[[T; 1]; 1]>
}

pub struct Grow<T: Next> {
    value: T,
    next: *T::Out,
}

fn value(grow: Grow<u256>) -> u256 {
    grow.value
}

pub struct Count<const N: u256> {
    value: u256,
    next: *Count<{ N + 1 }>,
}

fn count(counter: Count<0>) -> u256 {
    counter.value
}
