if b {} else {}

if b {} else {
    let x = 1
    x
}

if b {
    let x = 1
    x
} else {}

if b {
    let x = 1
    x
}

if b {
    let x = 1
    x
} else {
    let y = 1
    y
}

if match x {
    Scope::Parent => true
    Scope::Child => false
} {
    return 
} else {
    1
}

if let Some(Point { x, y }) = p {
    x + y
} else {
    0
}

if let Some(x) = p {
    x
} else if let Some(y) = q {
    y
} else {
    0
}

if let Option::Some(Point { x, y }) = p {
    x + y
} else {
    0
}
