[package]
name = "fe-parser"
version = "0.26.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Parser lib for Fe."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more.workspace = true
lazy_static = { workspace = true }
logos = { workspace = true }
rowan = { workspace = true }
rustc-hash.workspace = true
smallvec.workspace = true
unwrap-infallible = { workspace = true }

[dev-dependencies]
dir-test.workspace = true
wasm-bindgen-test.workspace = true
test-utils.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
