use core::abi::{AbiDecoder, AbiSize, AbiSpan, ByteInput, Decode, Encode, store_word}
use std::abi::{Bytes, Sol, SolCompat}
use std::evm::revert_empty

pub enum Mode {
    On,
    Off,
}

impl SolCompat for Mode {
    type S = String<5>
    const SOL_TYPE: Self::S = "uint8"
}

impl AbiSize for Mode {
    const HEAD_SIZE: u256 = 32
    const IS_DYNAMIC: bool = false
}

impl AbiSpan<Sol> for Mode {
    fn payload_end<I: ByteInput>(_ input: I, base: u256, pos: u256) -> u256 {
        pos + 32
    }
}

impl Decode<Sol> for Mode {
    fn decode_payload<D: AbiDecoder<Sol>>(_ d: mut D) -> Self {
        match d.read_word() {
            0 => Mode::On,
            1 => Mode::Off,
            _ => revert_empty(),
        }
    }
}

impl Encode<Sol> for Mode {
    fn encode(own self, _ ptr: *u8) {
        let value: u256 = match self {
            Mode::On => 0,
            Mode::Off => 1,
        }
        store_word(ptr, value)
    }
}

msg FooMsg {
    #[selector = sol("postOp(uint8,bytes,uint256,uint256)")]
    PostOp { mode: Mode, context: Bytes, actualGasCost: u256, actualUserOpFeePerGas: u256 } -> Mode,
}

pub contract Foo {
    recv FooMsg {
        PostOp { mode, context, actualGasCost, actualUserOpFeePerGas } -> Mode {
            mode
        }
    }
}
