[package]
name = "vyper-compiler"
version = "0.1.0"
authors = ["Grant Wuerker <gwuerker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yultsur = { git = "https://github.com/g-r-a-n-t/yultsur" }
vyper-parser = {path = "../parser", version = "0.1.0"}
