[package]
name = "fe-macros"
authors = ["The Fe Project Developers"]
version = "0.23.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Provides procudural macros for Fe lang."

[lib]
proc_macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
glob = "0.3"
