struct Foo { x: u32 }
impl core::ops::Eq for Foo {
    fn eq(self, _ other: Self) -> bool {
        self.x == other.x
    }
}

fn example() -> bool {
    let o = Some(Foo{ x: 1 })
    let o2: Option<ref Foo> = borrow_opt(o)
    let f = take_opt(o)

    o2.unwrap().x == f.x
}

fn borrow_opt(o: Option<Foo>) -> Option<ref Foo> {
    match o {
        Some(f) => { Some(ref f) }
        None => None
    }
}

fn take_opt(o: own Option<Foo>) -> Foo {
    o.unwrap_or(Foo { x: 0 })
}
