trait Sized {
    const SIZE: u256
}

struct Small {}
impl Sized for Small {
    const SIZE: u256 = 1
}

struct Big {}
impl Sized for Big {
    const SIZE: u256 = 100
}

trait Bounded {
    fn check<T>() where T: Sized, T::SIZE >= 50
}

struct Checker {}
impl Bounded for Checker {
    fn check<T>() where T: Sized, T::SIZE >= 50 {}
}

fn call_ok() {
    Checker::check<Big>()
}

fn call_fail() {
    Checker::check<Small>()
}
