use stuff::calculations::{ return_three, return_four }
use stuff::calculations::ambiguous;

/// ## `return_seven`
/// ### a function of numbers
/// #### returns the 3+4=7
pub fn return_seven() {
  return_three() + return_four()
}

fn calculate() {
  return_seven()
  let x: stuff::calculations::ambiguous
}

/// Anything that can be calculated ought to implement a
/// `calculate` function
pub trait Calculatable {
  fn calculate(self) -> i32
}

/// A struct for holding numbers like `x` and `y`
struct Numbers {
  x: i32,
  y: i32
}

fn add(x: i32, y: i32) -> i32 {
    x + y
}

impl Calculatable for Numbers {
  fn calculate(self) -> i32 {
      let z = self.x
      let w = self.y
      add(z, w)
  }
}
