struct S<const ROOT: u256 = _> {}
struct P<const ROOT: u256 = _> {}
struct A<const ROOT: u256 = _> {}
struct B<const ROOT: u256 = _> {}

trait Bound<T> {}

trait T {
    fn f<X, Y>(self, x: X, y: Y, p: P) uses (a: A, b: B)
    where
        X: Bound<A>,
        Y: Bound<B>
}

impl T for S {
    fn f<X, Y>(self, x: X, y: Y, p: P) uses (b: B, a: A)
    where
        Y: Bound<B>,
        X: Bound<A>
    {}
}
